
#-- https://circleci.com --#

version: 2

globals: &globals
  working_directory: /tmp/build
  docker:
      - image: ulidtko/rpm-shelf-ci

jobs:
  build:
    <<: *globals
    steps:
      - checkout

      - run:
          name: Fetch source tarballs
          command: |
            (mkdir -p SOURCES; cd SOURCES;
              for spec in ../SPECS/*.spec; do
                spectool -g $spec;
              done)

      - run:
          name: Install build-deps
          command: |
            for spec in SPECS/*.spec; do
              yum-builddep -y $spec;
            done

      - run:
          name: rpmbuild
          command: |
            for spec in SPECS/*.spec; do
              rpmbuild --define "_topdir $PWD" -ba $spec
            done

      - persist_to_workspace:
          root: .
          paths:
            - SRPMS
            - RPMS

  publish:
    <<: *globals
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Publish to GitHub
          command: |
            ghr -t $GITHUB_TOKEN \
                -u $CIRCLE_PROJECT_USERNAME \
                -r $CIRCLE_PROJECT_REPONAME \
                -prerelease \
                -replace \
                0.1 SRPMS/
      - run:
          name: PackageCloud upload
          command: |
            cd RPMS/x86_64
            package_cloud yank rpm-shelf/main/el/7 *.rpm
            package_cloud push rpm-shelf/main/el/7 *.rpm

workflows:
  version: 2
  all-there-is-to-it:
    jobs:
      - build
      - publish:
          requires:
            - build

