
#-- https://circleci.com --#

version: 2
jobs:
  build:
    docker:
      - image: centos:latest
    steps:
      - run:
          name: Install build-deps
          command: yum --noplugins install -y rpmdevtools yum-utils; yum clean all
      - checkout
      - run:
          name: Fetch source tarballs
          command: spectool -g SPECS/upx.spec
      - run:
          name: Start rpmbuild
          command: rpmbuild --define "_topdir $PWD" -bs SPECS/upx.spec
