
#-- https://circleci.com --#

version: 2

globals: &globals
  working_directory: /tmp/build
  docker:
      - image: ulidtko/rpm-shelf-ci

jobs:
  build:
    <<: *globals
    steps:
      - checkout

      - run:
          name: Fetch source tarballs
          command: |
            (mkdir -p SOURCES; cd SOURCES; spectool -g ../SPECS/upx.spec)

      - run:
          name: Install build-deps
          command: yum-builddep -y SPECS/upx.spec

      - run:
          name: rpmbuild
          command: rpmbuild --define "_topdir $PWD" -ba SPECS/upx.spec

      - persist_to_workspace:
          root: .
          paths:
            - SRPMS
            - RPMS

  publish:
    <<: *globals
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Publish to GitHub
          command: |
            ghr -t $GITHUB_TOKEN \
                -u $CIRCLE_PROJECT_USERNAME \
                -r $CIRCLE_PROJECT_REPONAME \
                -prerelease \
                -replace \
                0.1 SRPMS/
      - run:
          name: PackageCloud upload
          command: |
            package_cloud push rpm-shelf/main/el/7 RPMS/x86_64/upx-*.rpm

workflows:
  version: 2
  all-there-is-to-it:
    jobs:
      - build
      - publish:
          requires:
            - build

